Repository ExpDev07/coronavirus-tracker-api, pull requests merged in 2020-04, with the labels that each got.

#243 Add contribution guide
  CONTRIBUTING.md
Labels: dev, documentation

#254 Address Linting warnings
  Makefile
  app/__init__.py
  app/config/settings.py
  app/coordinates.py
  app/data/__init__.py
  app/location/__init__.py
  app/location/csbs.py
  app/main.py
  app/router/__init__.py
  app/router/v1/__init__.py
  app/router/v1/all.py
  app/router/v1/confirmed.py
  app/router/v1/deaths.py
  app/router/v1/recovered.py
  app/router/v2/__init__.py
  app/router/v2/latest.py
  app/router/v2/locations.py
  app/router/v2/sources.py
  app/services/location/__init__.py
  app/services/location/csbs.py
  app/services/location/jhu.py
  app/timeline.py
  app/utils/countries.py
  app/utils/date.py
  app/utils/populations.py
  pylintrc
  tests/test_countries.py
Labels: dev

#256 #232: Make all endpoints async
  .gitignore
  Pipfile
  Pipfile.lock
  app/main.py
  app/router/v1/all.py
  app/router/v1/confirmed.py
  app/router/v1/deaths.py
  app/router/v1/recovered.py
  app/router/v2/latest.py
  app/router/v2/locations.py
  app/services/location/__init__.py
  app/services/location/csbs.py
  app/services/location/jhu.py
  app/utils/httputils.py
  tests/conftest.py
  tests/example_data/covid19_county.csv
  tests/test_csbs.py
  tests/test_httputils.py
  tests/test_jhu.py
  tests/test_routes.py
Labels: performance

#252 Add docker compatibility
  .dockerignore
  Dockerfile
  docker-compose.yml
Labels: dev, enhancement

#272 Fix COPY on dockerfile.
  Dockerfile
  docker-compose.yml
Labels: docker

#273 Fix Docker ports & Gunicorn
  Dockerfile
  README.md
  docker-compose.yml
  tasks.py
Labels: dev, docker

#259 Source NYT
  README.md
  app/data/__init__.py
  app/enums/sources.py
  app/location/nyt.py
  app/services/location/nyt.py
  tests/example_data/counties.csv
  tests/expected_output/nyt_locations.json
  tests/test_nyt.py
  tests/test_routes.py
Labels: enhancement, source: nyt

#282 Uvicorn based Docker
  README.md
  uvicorn.Dockerfile
Labels: dev, docker

#294 add GZIP support for responses > 1000bytes
  app/__init__.py
  app/main.py
Labels: performance

#290 add minimal logging for location services
  app/services/location/csbs.py
  app/services/location/jhu.py
  app/services/location/nyt.py
Labels: down

#289 Refactor
  app/__init__.py
  app/enums/sources.py
  app/main.py
  app/models.py
  app/models/latest.py
  app/models/timeline.py
  app/router/__init__.py
  app/router/v1/__init__.py
  app/router/v1/all.py
  app/router/v1/confirmed.py
  app/router/v1/deaths.py
  app/router/v1/recovered.py
  app/router/v2/__init__.py
  app/router/v2/latest.py
  app/router/v2/sources.py
  app/routers/__init__.py
  app/routers/v1.py
  app/routers/v2.py
  app/services/location/csbs.py
  app/services/location/jhu.py
  app/services/location/nyt.py
  app/utils/countries.py
  app/utils/populations.py
Labels: dev

#295 Gunicorn with 4 workers
  Procfile
  app/services/location/jhu.py
  app/utils/countries.py
Labels: performance

#306 Use shared Redis cache for jhu data
  .env.example
  Pipfile
  Pipfile.lock
  app/caches.py
  app/config.py
  app/config/__init__.py
  app/config/settings.py
  app/io.py
  app/main.py
  app/services/location/jhu.py
  pylintrc
  pyproject.toml
  requirements-dev.txt
  requirements.txt
  tasks.py
  tests/test_io.py
Labels: down, enhancement, source: jhu
