Repository ExpDev07/coronavirus-tracker-api, pull requests merged in 2020-03, with the labels that each got.

#15 Add two letter country codes to `:locations` according to ISO_3166-1
  app/data/__init__.py
  app/data/countrycodes.py
Labels: enhancement

#192 No locations data 404
  app/router/locations.py
  tests/test_routes.py
Labels: source: jhu

#202 pipenv installation instructions
  README.md
Labels: documentation

#239 update dependencies and add coverage reporting
  .travis.yml
  Makefile
  Pipfile
  Pipfile.lock
  README.md
  app/__init__.py
  app/core.py
  app/main.py
Labels: documentation
